trigger:
  branches:
    include: [ main ]

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: SQL_Credentials

steps:
- checkout: self

- script: echo "Repo checked out successfully!"
  displayName: 'Initial check'

# Install SQL tools
- task: CmdLine@2
  displayName: 'Install sqlcmd'
  inputs:
    script: |
      sudo apt-get update
      sudo ACCEPT_EULA=Y apt-get install -y mssql-tools18 unixodbc-dev
      echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
      source ~/.bashrc
      /opt/mssql-tools18/bin/sqlcmd -?

# Load first 50 rows (brand-detail)
- task: CmdLine@2
  displayName: 'Load first 50 rows (brand-detail)'
  inputs:
    script: |
      head -n 51 "$(System.DefaultWorkingDirectory)/MIS281N_git_HW/brand-detail-url-etc_0_0_0.csv" > temp.csv
      /opt/mssql-tools18/bin/sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -d $SQL_DB -Q "
        IF OBJECT_ID('brand_detail_stage') IS NULL
          CREATE TABLE brand_detail_stage(line NVARCHAR(MAX));
        BULK INSERT brand_detail_stage
        FROM '$(System.DefaultWorkingDirectory)/MIS281N_git_HW/temp.csv'
        WITH (FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', FIRSTROW = 2);
      "

# Load first 50 rows (daily-spend)
- task: CmdLine@2
  displayName: 'Load first 50 rows (daily-spend)'
  inputs:
    script: |
      head -n 51 "$(System.DefaultWorkingDirectory)/MIS281N_git_HW/2021-01-19--data_01be88c2-0306-48b3-0042-fa0703282ad6_1304_5_0.csv" > temp2.csv
      /opt/mssql-tools18/bin/sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -d $SQL_DB -Q "
        IF OBJECT_ID('daily_spend_stage') IS NULL
          CREATE TABLE daily_spend_stage(line NVARCHAR(MAX));
        BULK INSERT daily_spend_stage
        FROM '$(System.DefaultWorkingDirectory)/MIS281N_git_HW/temp2.csv'
        WITH (FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', FIRSTROW = 2);
      "
