trigger:
  branches:
    include: [ main ]

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: SQL_Credentials

steps:
- checkout: self

- script: echo "Repo checked out successfully!"
  displayName: 'Initial check'

# Install SQL command-line tools
- task: CmdLine@2
  displayName: 'Install sqlcmd'
  inputs:
    script: |
      sudo apt-get update
      sudo apt-get install -y mssql-tools unixodbc-dev
      echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
      source ~/.bashrc

# Load first 50 rows of brand-detail
- task: CmdLine@2
  displayName: 'Load first 50 rows (brand-detail)'
  inputs:
    script: |
      head -n 51 rawdata/brand-detail-url-etc_0_0_0.csv > temp.csv
      sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -d $SQL_DB -Q "
        IF OBJECT_ID('brand_detail_stage') IS NULL
          CREATE TABLE brand_detail_stage(line NVARCHAR(MAX));
        BULK INSERT brand_detail_stage
        FROM '$(System.DefaultWorkingDirectory)/temp.csv'
        WITH (FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', FIRSTROW = 2);
      "

# Load first 50 rows of daily-spend
- task: CmdLine@2
  displayName: 'Load first 50 rows (daily-spend)'
  inputs:
    script: |
      head -n 51 rawdata/2021-01-19--data_01be88c2-0306-48b3-0042-fa0703282ad6_1304_5_0.csv > temp2.csv
      sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -d $SQL_DB -Q "
        IF OBJECT_ID('daily_spend_stage') IS NULL
          CREATE TABLE daily_spend_stage(line NVARCHAR(MAX));
        BULK INSERT daily_spend_stage
        FROM '$(System.DefaultWorkingDirectory)/temp2.csv'
        WITH (FIELDTERMINATOR = ',', ROWTERMINATOR = '\n', FIRSTROW = 2);
      "